/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminSessionEntityControllerFindAllOrder =
  (typeof AdminSessionEntityControllerFindAllOrder)[keyof typeof AdminSessionEntityControllerFindAllOrder];

export const AdminSessionEntityControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
