/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { AdminAccountEntityControllerFindAllOrder } from './adminAccountEntityControllerFindAllOrder';

export type AdminAccountEntityControllerFindAllParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Items per page
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * Field name to sort by
   */
  sort?: string;
  /**
   * Sort order
   */
  order?: AdminAccountEntityControllerFindAllOrder;
  /**
   * JSON string with filter criteria
   */
  filter?: string;
};
