/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { AdminUsersControllerFindAllOrder } from './adminUsersControllerFindAllOrder';

export type AdminUsersControllerFindAllParams = {
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  sort?: string;
  order?: AdminUsersControllerFindAllOrder;
  filter?: string;
};
