/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminUsersControllerFindAllOrder =
  (typeof AdminUsersControllerFindAllOrder)[keyof typeof AdminUsersControllerFindAllOrder];

export const AdminUsersControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
