/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminAccountEntityControllerFindAllOrder =
  (typeof AdminAccountEntityControllerFindAllOrder)[keyof typeof AdminAccountEntityControllerFindAllOrder];

export const AdminAccountEntityControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
