/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type AdminVerificationEntityControllerFindAllOrder =
  (typeof AdminVerificationEntityControllerFindAllOrder)[keyof typeof AdminVerificationEntityControllerFindAllOrder];

export const AdminVerificationEntityControllerFindAllOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
