/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UserEntity } from './userEntity';

export type AdminUsersControllerFindAll200 = {
  data: UserEntity[];
  total: number;
  page: number;
  perPage: number;
};
