/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type ChangeEmailBody = {
  /** The new email address to set must be a valid email address */
  newEmail: string;
  /** The URL to redirect to after email verification */
  callbackURL?: string | null;
};
