/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ChangePassword200User } from './changePassword200User';

export type ChangePassword200 = {
  /** New session token if other sessions were revoked */
  token?: string | null;
  user: ChangePassword200User;
};
