/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Status message of the email change process
 */
export type ChangeEmail200Message =
  | (typeof ChangeEmail200Message)[keyof typeof ChangeEmail200Message]
  | null;

export const ChangeEmail200Message = {
  Email_updated: 'Email updated',
  Verification_email_sent: 'Verification email sent',
} as const;
