/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ChangeEmail200Message } from './changeEmail200Message';
import type { User } from './user';

export type ChangeEmail200 = {
  user?: User;
  /** Indicates if the request was successful */
  status: boolean;
  /** Status message of the email change process */
  message?: ChangeEmail200Message;
};
