/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type CreateProductDtoMetadataDimensions = {
  /** @exclusiveMinimum 0 */
  width: number;
  /** @exclusiveMinimum 0 */
  height: number;
  /** @exclusiveMinimum 0 */
  depth: number;
};
