/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type CreateProductDtoCurrency =
  (typeof CreateProductDtoCurrency)[keyof typeof CreateProductDtoCurrency];

export const CreateProductDtoCurrency = {
  USD: 'USD',
  EUR: 'EUR',
  RUB: 'RUB',
} as const;
