/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { DeleteUser200Message } from './deleteUser200Message';

export type DeleteUser200 = {
  /** Indicates if the operation was successful */
  success: boolean;
  /** Status message of the deletion process */
  message: DeleteUser200Message;
};
