/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type DeleteUserBody = {
  /** The callback URL to redirect to after the user is deleted */
  callbackURL?: string;
  /** The user's password. Required if session is not fresh */
  password?: string;
  /** The deletion verification token */
  token?: string;
};
