/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Application error code for i18n and client-side handling
 */
export type ErrorResponseDtoCode = (typeof ErrorResponseDtoCode)[keyof typeof ErrorResponseDtoCode];

export const ErrorResponseDtoCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_VALIDATION_ERROR: 'DATABASE_VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  DATABASE_CONFLICT_ERROR: 'DATABASE_CONFLICT_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;
