/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export interface ErrorDetailsDto {
  /** Database constraint name (e.g., "users_email_key") */
  constraint?: string;
  /** Database table name */
  table?: string;
  /** Database column name */
  column?: string;
  /** PostgreSQL error detail message */
  detail?: string;
}
