/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ErrorDetailsDto } from './errorDetailsDto';
import type { ErrorResponseDtoCode } from './errorResponseDtoCode';
import type { ValidationErrorDto } from './validationErrorDto';

export interface ErrorResponseDto {
  /** HTTP status code */
  status: number;
  /** Application error code for i18n and client-side handling */
  code: ErrorResponseDtoCode;
  /** Human-readable error message (English) */
  message: string;
  /** ISO 8601 timestamp */
  timestamp: string;
  /** Request path */
  path: string;
  /** Request ID for tracing */
  requestId?: string;
  /** Field-level validation errors (for forms) */
  validation?: ValidationErrorDto[];
  /** Additional error details (constraint, table, column, etc.) */
  details?: ErrorDetailsDto;
}
