/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { GetAuthAccountInfo200Data } from './getAuthAccountInfo200Data';
import type { GetAuthAccountInfo200User } from './getAuthAccountInfo200User';

export type GetAuthAccountInfo200 = {
  user: GetAuthAccountInfo200User;
  data: GetAuthAccountInfo200Data;
};
