/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type GetAuthDeleteUserCallbackParams = {
  /**
   * The token to verify the deletion request
   */
  token?: string;
  /**
   * The URL to redirect to after deletion
   */
  callbackURL?: string | null;
};
