/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type GetAuthVerifyEmailParams = {
  /**
   * The token to verify the email
   */
  token: string;
  /**
   * The URL to redirect to after email verification
   */
  callbackURL?: string;
};
