/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { GetAuthDeleteUserCallback200Message } from './getAuthDeleteUserCallback200Message';

export type GetAuthDeleteUserCallback200 = {
  /** Indicates if the deletion was successful */
  success: boolean;
  /** Confirmation message */
  message: GetAuthDeleteUserCallback200Message;
};
