/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Confirmation message
 */
export type GetAuthDeleteUserCallback200Message =
  (typeof GetAuthDeleteUserCallback200Message)[keyof typeof GetAuthDeleteUserCallback200Message];

export const GetAuthDeleteUserCallback200Message = {
  User_deleted: 'User deleted',
} as const;
