/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Intended use of the public key (e.g., 'sig' for signature)
 */
export type GetJSONWebKeySet200KeysItemUse =
  | (typeof GetJSONWebKeySet200KeysItemUse)[keyof typeof GetJSONWebKeySet200KeysItemUse]
  | null;

export const GetJSONWebKeySet200KeysItemUse = {
  sig: 'sig',
} as const;
