/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { GetJSONWebKeySet200KeysItemUse } from './getJSONWebKeySet200KeysItemUse';

export type GetJSONWebKeySet200KeysItem = {
  /** Key ID uniquely identifying the key, corresponds to the 'id' from the stored Jwk */
  kid: string;
  /** Key type (e.g., 'RSA', 'EC', 'OKP') */
  kty: string;
  /** Algorithm intended for use with the key (e.g., 'EdDSA', 'RS256') */
  alg: string;
  /** Intended use of the public key (e.g., 'sig' for signature) */
  use?: GetJSONWebKeySet200KeysItemUse;
  /** Modulus for RSA keys (base64url-encoded) */
  n?: string | null;
  /** Exponent for RSA keys (base64url-encoded) */
  e?: string | null;
  /** Curve name for elliptic curve keys (e.g., 'Ed25519', 'P-256') */
  crv?: string | null;
  /** X coordinate for elliptic curve keys (base64url-encoded) */
  x?: string | null;
  /** Y coordinate for elliptic curve keys (base64url-encoded) */
  y?: string | null;
};
