/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { GetJSONWebKeySet200KeysItem } from './getJSONWebKeySet200KeysItem';

export type GetJSONWebKeySet200 = {
  /** Array of public JSON Web Keys */
  keys: GetJSONWebKeySet200KeysItem[];
};
