/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ProductResponseDto } from './productResponseDto';

export interface GetProductResponseDto {
  product: ProductResponseDto;
  isOwner: boolean;
}
