/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type HealthControllerCheck503Details = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
};
