/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck503Details } from './healthControllerCheck503Details';
import type { HealthControllerCheck503Error } from './healthControllerCheck503Error';
import type { HealthControllerCheck503Info } from './healthControllerCheck503Info';

export type HealthControllerCheck503 = {
  status?: string;
  info?: HealthControllerCheck503Info;
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};
