/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type LinkSocialAccount200 = {
  /** The authorization URL to redirect the user to */
  url?: string;
  /** Indicates if the user should be redirected to the authorization URL */
  redirect: boolean;
  status?: boolean;
};
