/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LinkSocialAccountBodyIdToken } from './linkSocialAccountBodyIdToken';

export type LinkSocialAccountBody = {
  /** The URL to redirect to after the user has signed in */
  callbackURL?: string | null;
  provider: string;
  idToken?: LinkSocialAccountBodyIdToken;
  requestSignUp?: boolean | null;
  /** Additional scopes to request from the provider */
  scopes?: string[] | null;
  /** The URL to redirect to if there is an error during the link process */
  errorCallbackURL?: string | null;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: boolean | null;
  additionalData?: string | null;
};
