/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { PaginationDto } from './paginationDto';
import type { ProductResponseDto } from './productResponseDto';

export interface PaginatedProductsResponseDto {
  data: ProductResponseDto[];
  pagination: PaginationDto;
}
