/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export type PostAuthEmailOtpVerifyEmail200 = {
  /** Indicates if the verification was successful */
  status: boolean;
  /** Session token if autoSignInAfterVerification is enabled, otherwise null */
  token: string | null;
  user: User;
};
