/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type PostAuthRevokeOtherSessions200 = {
  /** Indicates if all other sessions were revoked successfully */
  status: boolean;
};
