/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type PostAuthGetAccessTokenBody = {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /** The account ID associated with the refresh token */
  accountId?: string | null;
  /** The user ID associated with the account */
  userId?: string | null;
};
