/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllStatus =
  (typeof ProductsControllerFindAllStatus)[keyof typeof ProductsControllerFindAllStatus];

export const ProductsControllerFindAllStatus = {
  draft: 'draft',
  active: 'active',
  archived: 'archived',
  out_of_stock: 'out_of_stock',
} as const;
