/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerGetMineCategory =
  (typeof ProductsControllerGetMineCategory)[keyof typeof ProductsControllerGetMineCategory];

export const ProductsControllerGetMineCategory = {
  electronics: 'electronics',
  clothing: 'clothing',
  food: 'food',
  books: 'books',
  toys: 'toys',
  other: 'other',
} as const;
