/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ProductResponseDtoCategory } from './productResponseDtoCategory';
import type { ProductResponseDtoCurrency } from './productResponseDtoCurrency';
import type { ProductResponseDtoMetadata } from './productResponseDtoMetadata';
import type { ProductResponseDtoStatus } from './productResponseDtoStatus';

export interface ProductResponseDto {
  id: string;
  name: string;
  description?: string;
  price: number;
  currency: ProductResponseDtoCurrency;
  category: ProductResponseDtoCategory;
  status: ProductResponseDtoStatus;
  inStock: boolean;
  stockQuantity?: number;
  tags?: string[];
  imageUrl?: string;
  discountPercentage?: number;
  metadata?: ProductResponseDtoMetadata;
  publishedAt?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}
