/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllSortBy =
  (typeof ProductsControllerFindAllSortBy)[keyof typeof ProductsControllerFindAllSortBy];

export const ProductsControllerFindAllSortBy = {
  name: 'name',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
