/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerGetMineSortBy =
  (typeof ProductsControllerGetMineSortBy)[keyof typeof ProductsControllerGetMineSortBy];

export const ProductsControllerGetMineSortBy = {
  name: 'name',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
