/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllSortOrder =
  (typeof ProductsControllerFindAllSortOrder)[keyof typeof ProductsControllerFindAllSortOrder];

export const ProductsControllerFindAllSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
