/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type ResetPasswordWithEmailOTPBody = {
  /** Email address to reset the password */
  email: string;
  /** OTP sent to the email */
  otp: string;
  /** New password */
  password: string;
};
