/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type ResetPasswordCallbackParams = {
  /**
   * The URL to redirect the user to reset their password
   */
  callbackURL: string;
};
