/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type SendVerificationEmailBody = {
  /** The email to send the verification email to */
  email: string;
  /** The URL to use for email verification callback */
  callbackURL?: string | null;
};
