/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type SendEmailVerificationOTPBody = {
  /** Email address to send the OTP */
  email: string;
  /** Type of the OTP */
  type: string;
};
