/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export interface Session {
  id?: string;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  ipAddress?: string;
  userAgent?: string;
  userId: string;
}
