/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type SignUpWithEmailAndPasswordBody = {
  /** The name of the user */
  name: string;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The profile image URL of the user */
  image?: string;
  /** The URL to use for email verification callback */
  callbackURL?: string;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean;
};
