/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type SignInWithEmailOTPBody = {
  /** Email address to sign in */
  email: string;
  /** OTP sent to the email */
  otp: string;
};
