/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type SignInEmailBody = {
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
  /** Callback URL to use as a redirect for email verification */
  callbackURL?: string | null;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean | null;
};
