/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { SignUpWithEmailAndPassword200User } from './signUpWithEmailAndPassword200User';

export type SignUpWithEmailAndPassword200 = {
  /** Authentication token for the session */
  token?: string | null;
  user: SignUpWithEmailAndPassword200User;
};
