/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export type SignInWithEmailOTP200 = {
  /** Session token for the authenticated session */
  token: string;
  user: User;
};
