/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

/**
 * Session response when idToken is provided
 */
export type SignInEmail200 = {
  redirect: boolean;
  /** Session token */
  token: string;
  url?: string | null;
  user: User;
};
