/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

/**
 * Session response when idToken is provided
 */
export type SocialSignIn200 = {
  token: string;
  user: User;
  url?: string;
  redirect: boolean;
};
