/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type SocialSignInBodyIdToken = {
  /** ID token from the provider */
  token: string;
  /** Nonce used to generate the token */
  nonce?: string | null;
  /** Access token from the provider */
  accessToken?: string | null;
  /** Refresh token from the provider */
  refreshToken?: string | null;
  /** Expiry date of the token */
  expiresAt?: number | null;
} | null;
