/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { SocialSignInBodyIdToken } from './socialSignInBodyIdToken';

export type SocialSignInBody = {
  /** Callback URL to redirect to after the user has signed in */
  callbackURL?: string | null;
  newUserCallbackURL?: string | null;
  /** Callback URL to redirect to if an error happens */
  errorCallbackURL?: string | null;
  provider: string;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: boolean | null;
  idToken?: SocialSignInBodyIdToken;
  /** Array of scopes to request from the provider. This will override the default scopes passed. */
  scopes?: string[] | null;
  /** Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider */
  requestSignUp?: boolean | null;
  /** The login hint to use for the authorization code request */
  loginHint?: string | null;
  additionalData?: string | null;
};
