/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductDtoMetadataDimensions } from './updateProductDtoMetadataDimensions';

export type UpdateProductDtoMetadata = {
  /** @minLength 1 */
  brand?: string;
  /** @minLength 1 */
  manufacturer?: string;
  /** @minLength 1 */
  sku?: string;
  /** @minLength 1 */
  barcode?: string;
  /** @exclusiveMinimum 0 */
  weight?: number;
  dimensions?: UpdateProductDtoMetadataDimensions;
};
