/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */

export type UpdateProductDtoCurrency =
  (typeof UpdateProductDtoCurrency)[keyof typeof UpdateProductDtoCurrency];

export const UpdateProductDtoCurrency = {
  USD: 'USD',
  EUR: 'EUR',
  RUB: 'RUB',
} as const;
