/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Foundation API
 * NestJS Foundation API Documentation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export type UpdateUser200 = {
  user?: User;
};
