/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type UploadRequestDtoContext =
  (typeof UploadRequestDtoContext)[keyof typeof UploadRequestDtoContext];

export const UploadRequestDtoContext = {
  'user-photo': 'user-photo',
  'event-photo': 'event-photo',
  'organizer-logo': 'organizer-logo',
  'organizer-cover': 'organizer-cover',
  'venue-photo': 'venue-photo',
} as const;
