/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UploadRequestDtoContext } from './uploadRequestDtoContext';

export interface UploadRequestDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  filename: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  contentType: string;
  context: UploadRequestDtoContext;
}
