/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * NestJS Starter Boilerplate API
 * NestJS Starter Boilerplate API Documentation
 * OpenAPI spec version: 1.0
 */

export type VerifyEmailWithOTPBody = {
  /** Email address the OTP was sent to */
  email: string;
  /** Type of the OTP */
  type: string;
  /** OTP to verify */
  otp: string;
};
