import type { OpenAPIV3_1 } from 'openapi-types';
import { expect, test } from './fixtures';
import { dereferenceSpec } from './helpers/schema-validator';

type PathItemObject = OpenAPIV3_1.PathItemObject;
type OperationObject = OpenAPIV3_1.OperationObject;

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

function forEachOperation(
  paths: Record<string, PathItemObject>,
  callback: (path: string, method: string, operation: OperationObject) => void
): void {
  for (const [path, pathItem] of Object.entries(paths)) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method] as OperationObject | undefined;
      if (operation) callback(path, method, operation);
    }
  }
}

/**
 * Routes generated by Better Auth, admin CRUD framework, or Prometheus
 * that don't have manual @ApiOperation annotations.
 */
function isAutoGenerated(path: string, tags: string[]): boolean {
  return (
    tags.some((t) => t.toLowerCase() === 'auth') ||
    path.startsWith('/admin/') ||
    path.startsWith('/auth/') ||
    path === '/metrics'
  );
}

const EXPECTED_TAGS = [
  'App',
  'Events',
  'Geo',
  'Health',
  'Media',
  'Moderation',
  'Organizers',
  'Organizer Events',
  'User Profile',
  'Event Attendance',
  'Event Suggestions',
];

test.describe('Swagger Documentation', () => {
  test('should serve Swagger UI at /docs', async ({ useHttp }) => {
    const http = useHttp();
    const { status } = await http.get('/docs');

    expect(status).toBe(200);
  });

  test('should serve Swagger JSON at /docs-json', async ({ useHttp }) => {
    const http = useHttp();
    const { status, data } = await http.get('/docs-json');

    expect(status).toBe(200);
    expect(data).toBeDefined();
    expect(data.info).toBeDefined();
    expect(data.info.title).toBe('NestJS Foundation API');
    expect(data.paths).toBeDefined();
  });
});

test.describe('OpenAPI Spec Validation', () => {
  let specData: OpenAPIV3_1.Document;

  test.beforeAll(async ({ baseURL }) => {
    const response = await fetch(`${baseURL}/docs-json`);
    specData = (await response.json()) as OpenAPIV3_1.Document;
  });

  test('should resolve all $ref references', async () => {
    const dereferenced = await dereferenceSpec(specData);
    expect(dereferenced).toBeDefined();
    expect(dereferenced.paths).toBeDefined();
  });

  test('every hand-written operation should have a summary', () => {
    const missing: string[] = [];

    forEachOperation(specData.paths as Record<string, PathItemObject>, (path, method, op) => {
      if (isAutoGenerated(path, op.tags || [])) return;
      if (!op.summary) {
        missing.push(`${method.toUpperCase()} ${path}`);
      }
    });

    expect(
      missing,
      `Operations missing @ApiOperation summary:\n${missing.join('\n')}`
    ).toHaveLength(0);
  });

  test('every hand-written operation should have an operationId', () => {
    const missing: string[] = [];

    forEachOperation(specData.paths as Record<string, PathItemObject>, (path, method, op) => {
      if (isAutoGenerated(path, op.tags || [])) return;
      if (!op.operationId) {
        missing.push(`${method.toUpperCase()} ${path}`);
      }
    });

    expect(missing, `Operations missing operationId:\n${missing.join('\n')}`).toHaveLength(0);
  });

  test('every hand-written 2xx JSON response should have content schema', () => {
    const missing: string[] = [];

    // Endpoints that intentionally return non-JSON (plain text, no body)
    const NON_JSON_ENDPOINTS = new Set(['GET /']);

    forEachOperation(specData.paths as Record<string, PathItemObject>, (path, method, op) => {
      if (isAutoGenerated(path, op.tags || [])) return;
      const key = `${method.toUpperCase()} ${path}`;
      if (NON_JSON_ENDPOINTS.has(key)) return;

      const responses = op.responses || {};
      for (const [status, responseRef] of Object.entries(responses)) {
        const statusNum = Number(status);
        if (statusNum >= 200 && statusNum < 300 && statusNum !== 204 && statusNum !== 200) {
          const response = responseRef as OpenAPIV3_1.ResponseObject;
          if (!response.content) {
            missing.push(`${key} → ${status}`);
          }
        }
      }
    });

    expect(missing, `2xx responses missing content schema:\n${missing.join('\n')}`).toHaveLength(0);
  });

  test('error responses missing description should not increase', () => {
    const missing: string[] = [];

    forEachOperation(specData.paths as Record<string, PathItemObject>, (path, method, op) => {
      if (isAutoGenerated(path, op.tags || [])) return;
      const responses = op.responses || {};
      for (const [status, responseRef] of Object.entries(responses)) {
        const statusNum = Number(status);
        if (statusNum >= 400) {
          const response = responseRef as OpenAPIV3_1.ResponseObject;
          if (!response.description) {
            missing.push(`${method.toUpperCase()} ${path} → ${status}`);
          }
        }
      }
    });

    // Baseline: 37 endpoints currently missing error descriptions.
    // This test prevents regressions — the count should only decrease as descriptions are added.
    expect(
      missing.length,
      `Error responses without description (was 37):\n${missing.join('\n')}`
    ).toBeLessThanOrEqual(37);
  });

  test('every operation should have at least one response', () => {
    const missing: string[] = [];

    forEachOperation(specData.paths as Record<string, PathItemObject>, (path, method, op) => {
      if (!op.responses || Object.keys(op.responses).length === 0) {
        missing.push(`${method.toUpperCase()} ${path}`);
      }
    });

    expect(missing, `Operations without responses:\n${missing.join('\n')}`).toHaveLength(0);
  });
});

test.describe('Spec Stability', () => {
  let specData: OpenAPIV3_1.Document;

  test.beforeAll(async ({ baseURL }) => {
    const response = await fetch(`${baseURL}/docs-json`);
    specData = (await response.json()) as OpenAPIV3_1.Document;
  });

  test('should contain all expected API tags', () => {
    // Collect tags from operations since NestJS may not populate root-level tags array
    const usedTags = new Set<string>();
    forEachOperation(specData.paths as Record<string, PathItemObject>, (_path, _method, op) => {
      for (const tag of op.tags || []) usedTags.add(tag);
    });
    for (const tag of specData.tags || []) usedTags.add(tag.name);

    const missing = EXPECTED_TAGS.filter((tag) => !usedTags.has(tag));
    expect(missing, `Missing tags: ${missing.join(', ')}`).toHaveLength(0);
  });

  test('should have minimum path count', () => {
    const pathCount = Object.keys(specData.paths || {}).length;
    expect(pathCount).toBeGreaterThanOrEqual(10);
  });

  test('should have minimum operation count', () => {
    let operationCount = 0;
    forEachOperation(specData.paths as Record<string, PathItemObject>, () => {
      operationCount++;
    });
    expect(operationCount).toBeGreaterThanOrEqual(20);
  });

  test('should have minimum schema component count', () => {
    const schemas = (specData.components as OpenAPIV3_1.ComponentsObject)?.schemas || {};
    const schemaCount = Object.keys(schemas).length;
    expect(schemaCount).toBeGreaterThanOrEqual(10);
  });
});
